apiVersion: 1

datasources:
  - name: Supabase PostgreSQL
    uid: supabase-postgres
    type: postgres
    access: proxy
    isDefault: true
    editable: false
    url: ${DB_HOST}:${DB_PORT}
    user: ${DB_USER}
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      database: ${DB_DATABASE}
      sslmode: require
      postgresVersion: 1500
      timescaledb: false
